### ISSUE TITLE
Improve responsiveness of frontend

### ISSUE THREAD

**Issue by T-x-T** [T-x-T/TxTs-Treasury#41]
The frontend should be fully usable on a mobile phone and still look great on a large monitor

**Comment by bengiv** [comment]
> [...]on a large monitor
and on smaller ones like macbooks
see: https://discord.com/channels/624976691692961793/636931914892312587/1113893278803296262

**Comment by bengiv** [comment]
> The frontend should be fully usable on a mobile phone

Suggestions for that:
- Fadeable sidebar
- Automatically put dashboard chart under each other
- fullscreen edit/ add page

**Comment by T-x-T** [comment]
Implemented in 0.17.0
